## Loading data into Pandas DataFrame

In [14]:
import pandas as pd
import numpy as np

In [15]:
! gdown --id 1rsAH_B4iFuw_KuyhEFcF4uAqywe2Uq-f

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1rsAH_B4iFuw_KuyhEFcF4uAqywe2Uq-f
To: /content/cs_scientist_ranks.xlsx
100% 273k/273k [00:00<00:00, 17.3MB/s]

In [16]:
df = pd.read_excel("/content/cs_scientist_ranks.xlsx")
df.Citations = df.Citations.apply(lambda x : x.replace(',',''))
df

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
...,...,...,...,...,...,...,...,...,...,...
1995,1995,1996,192,Cheng-Zhong Xu,University of Macau,China,61,11960,514,https://s.research.com/images/d1652ee8cb26ff97...
1996,1996,1997,193,Debiao He,Wuhan University,China,61,11922,228,https://s.research.com/images/97930f238ef7d9b1...
1997,1997,1998,1082,Shuai Li,University of Oulu,Finland,61,11729,395,https://s.research.com/images/607b8a3af140d2e5...
1998,1998,1999,194,Cunsheng Ding,Hong Kong University of Science and Technology,China,61,11595,228,https://s.research.com/images/1c011d0a81a71824...
1999,1999,2000,79,Jonathan Li,University of Waterloo,Canada,61,11276,505,https://s.research.com/images/90a9c3c82b5717c5...

## DataFrames
DataFrame is very similar to Excel workbook Tabular Datasheets starting from index 0. <br/>

Operations: <br/>
i) **df.shape** => dimension of the dataframe <br/>
ii) **df.head(n)** => top n records/rows <br/>
iii) **df.tail(n)** => bottom n records/rows <br/>
iv) **df.columns** => all column names <br/>
v) **df['column_name']** => access data from particular column name <br/>
vi) **df[['column_name_1','column_name_2',...]]** => access data from multiple columns

In [17]:
df.shape

(2000, 10)

In [18]:
df.head(3) # default n=5

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...

In [19]:
df.tail(3) # default n=5

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
1997,1997,1998,1082,Shuai Li,University of Oulu,Finland,61,11729,395,https://s.research.com/images/607b8a3af140d2e5...
1998,1998,1999,194,Cunsheng Ding,Hong Kong University of Science and Technology,China,61,11595,228,https://s.research.com/images/1c011d0a81a71824...
1999,1999,2000,79,Jonathan Li,University of Waterloo,Canada,61,11276,505,https://s.research.com/images/90a9c3c82b5717c5...

In [20]:
df.columns

Index(['Unnamed: 0', 'World Rank', 'National Rank', 'Name', 'Affiliation',
       'Country', 'D-Index', 'Citations', 'Number of Publications',
       'Image URLs'],
      dtype='object')

In [21]:
df['Name']

0            Anil K. Jain
1           Yoshua Bengio
2              Jiawei Han
3       Michael I. Jordan
4        Andrew Zisserman
              ...
1995       Cheng-Zhong Xu
1996            Debiao He
1997             Shuai Li
1998        Cunsheng Ding
1999          Jonathan Li
Name: Name, Length: 2000, dtype: object

In [22]:
df[['Name','Affiliation']]

                   Name                                     Affiliation
0          Anil K. Jain                       Michigan State University
1         Yoshua Bengio                          University of Montreal
2            Jiawei Han      University of Illinois at Urbana-Champaign
3     Michael I. Jordan                        University of California
4      Andrew Zisserman                            University of Oxford
...                 ...                                             ...
1995     Cheng-Zhong Xu                             University of Macau
1996          Debiao He                                Wuhan University
1997           Shuai Li                              University of Oulu
1998      Cunsheng Ding  Hong Kong University of Science and Technology
1999        Jonathan Li                          University of Waterloo

[2000 rows x 2 columns]

## Indexing

In [23]:
df.iloc[:3]

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...

In [24]:
df.iloc[3]

Unnamed: 0                                                                3
World Rank                                                                4
National Rank                                                             3
Name                                                      Michael I. Jordan
Affiliation                                        University of California
Country                                                            Berkeley
D-Index                                                                 176
Citations                                                            220056
Number of Publications                                                  776
Image URLs                https://s.research.com/images/56e4335ff90165e8...
Name: 3, dtype: object

In [25]:
# Second top 50 Names, Image URLs and affiliation

df.iloc[51:101,2:5]

,National Rank,Name,Affiliation
51,4,Bernt Schiele,Max Planck Institute for Informatics
52,31,Albert-László Barabási,Northeastern University
53,32,Andrew Y. Ng,Stanford University
54,33,Deborah Estrin,Cornell University
55,1,Shuicheng Yan,National University of Singapore
56,6,Hong-Jiang Zhang,ByteDance
57,34,Hari Balakrishnan,MIT
58,35,Richard Szeliski,University of Washington
59,7,Qiang Yang,Hong Kong University of Science and Technology
60,36,Christos H. Papadimitriou,Columbia University
61,37,Dawn Song,University of California
62,1,Athanasios V. Vasilakos,Luleå University of Technology
63,38,David E. Culler,University of California
64,39,Ben Shneiderman,University of Maryland
65,40,Shih-Fu Chang,Columbia University
66,41,Kalyanmoy Deb,Michigan State University
67,42,Terrence J. Sejnowski,Salk Institute for Biological Studies
68,43,Dan Boneh,Stanford University
69,8,David Zhang,Chinese University of Hong Kong
70,5,Witold Pedrycz,University of Alberta
71,2,Didier Dubois,Paul Sabatier University
72,44,Li Fei-Fei,Stanford University
73,45,William T. Freeman,MIT
74,5,Wolfram Burgard,University of Freiburg
75,46,Larry S. Davis,University of Maryland
76,47,Shree K. Nayar,Columbia University
77,9,Xuelong Li,Northwestern Polytechnical University
78,48,Huan Liu,Arizona State University
79,49,Mario Gerla,University of California
80,50,John A. Stankovic,University of Virginia
81,51,Yann LeCun,Facebook (United States)
82,52,Antonio Torralba,MIT
83,53,Stephen Grossberg,Boston University
84,6,Hans-Peter Seidel,Max Planck Institute for Informatics
85,54,Shankar Sastry,University of California
86,55,Mubarak Shah,University of Central Florida
87,56,Zhu Han,University of Houston
88,10,Dinggang Shen,ShanghaiTech University
89,57,Alan L. Yuille,Johns Hopkins University
90,3,Henri Prade,Paul Sabatier University
91,58,Randy H. Katz,University of California
92,59,Sergey Levine,University of California
93,2,Luca Benini,ETH Zurich
94,60,Theodore S. Rappaport,New York University
95,61,H. Vincent Poor,Princeton University
96,7,Daniel Rueckert,Technical University of Munich
97,11,Xin Yao,Southern University of Science and Technology
98,62,MengChu Zhou,New Jersey Institute of Technology
99,3,Martin Vetterli,École Polytechnique Fédérale de Lausanne
100,63,Dieter Fox,University of Washington

In [26]:
# Same thing but in a different way
df[['Name', 'Image URLs', 'Affiliation']].iloc[51:101]

,Name,Image URLs,Affiliation
51,Bernt Schiele,https://s.research.com/images/41c1d9d732c58c3e...,Max Planck Institute for Informatics
52,Albert-László Barabási,https://s.research.com/images/27d8857b608d201a...,Northeastern University
53,Andrew Y. Ng,https://s.research.com/images/655f85eed1748af3...,Stanford University
54,Deborah Estrin,https://s.research.com/images/c003430f792bccdb...,Cornell University
55,Shuicheng Yan,https://s.research.com/images/fe2b011dcfed8f46...,National University of Singapore
56,Hong-Jiang Zhang,https://s.research.com/images/86cd0138a90d04ce...,ByteDance
57,Hari Balakrishnan,https://s.research.com/images/06ffc7e8aa355f47...,MIT
58,Richard Szeliski,https://s.research.com/images/eea998d7614c5445...,University of Washington
59,Qiang Yang,https://s.research.com/images/6856b85aba961817...,Hong Kong University of Science and Technology
60,Christos H. Papadimitriou,https://s.research.com/images/16e9bdfee66feaee...,Columbia University
61,Dawn Song,https://s.research.com/images/1fcccf5408e4997d...,University of California
62,Athanasios V. Vasilakos,https://s.research.com/images/2a6ad9cd2162fb88...,Luleå University of Technology
63,David E. Culler,https://s.research.com/images/535d3909dbd6b100...,University of California
64,Ben Shneiderman,https://s.research.com/images/3b6d2242c89dcf44...,University of Maryland
65,Shih-Fu Chang,https://s.research.com/images/6cb1e330a8f55532...,Columbia University
66,Kalyanmoy Deb,https://s.research.com/images/7d19bc2723c1d70b...,Michigan State University
67,Terrence J. Sejnowski,https://s.research.com/images/52c725b78f89f917...,Salk Institute for Biological Studies
68,Dan Boneh,https://s.research.com/images/ee88b4be7f20a9d8...,Stanford University
69,David Zhang,https://s.research.com/images/cf1fc77f0cf052d1...,Chinese University of Hong Kong
70,Witold Pedrycz,https://s.research.com/images/8f26754a6e28c7d6...,University of Alberta
71,Didier Dubois,https://s.research.com/images/624c73ccd8e178dc...,Paul Sabatier University
72,Li Fei-Fei,https://s.research.com/images/9d69f430e92b98f2...,Stanford University
73,William T. Freeman,https://s.research.com/images/326317bdf18dc7d5...,MIT
74,Wolfram Burgard,https://s.research.com/images/2a1bc099402e595a...,University of Freiburg
75,Larry S. Davis,https://s.research.com/images/288ef6347d1f4c86...,University of Maryland
76,Shree K. Nayar,https://s.research.com/images/76cadb621cb16db7...,Columbia University
77,Xuelong Li,https://s.research.com/images/fd4a5d6309035164...,Northwestern Polytechnical University
78,Huan Liu,https://s.research.com/images/4026325414f2d277...,Arizona State University
79,Mario Gerla,https://s.research.com/images/a8c2acaedf884b5e...,University of California
80,John A. Stankovic,https://s.research.com/images/1590827f1bb021b0...,University of Virginia
81,Yann LeCun,https://s.research.com/images/5c0738834ea07cf4...,Facebook (United States)
82,Antonio Torralba,https://s.research.com/images/f095ecfaca3d8a3c...,MIT
83,Stephen Grossberg,https://s.research.com/images/16b29e222a1d1fa6...,Boston University
84,Hans-Peter Seidel,https://s.research.com/images/601791e226ded01a...,Max Planck Institute for Informatics
85,Shankar Sastry,https://s.research.com/images/e46558f72304af00...,University of California
86,Mubarak Shah,https://s.research.com/images/28796efa4d47a629...,University of Central Florida
87,Zhu Han,https://s.research.com/images/f5cb08df012da76e...,University of Houston
88,Dinggang Shen,https://s.research.com/images/ef97d4d3301452c2...,ShanghaiTech University
89,Alan L. Yuille,https://s.research.com/images/2b128f77d826f6ea...,Johns Hopkins University
90,Henri Prade,https://s.research.com/images/6b6616deb7895c05...,Paul Sabatier University
91,Randy H. Katz,https://s.research.com/images/e79b04674c41d696...,University of California
92,Sergey Levine,https://s.research.com/images/8cdcafd81b87b9da...,University of California
93,Luca Benini,https://s.research.com/images/cf161bed6e9648e1...,ETH Zurich
94,Theodore S. Rappaport,https://s.research.com/images/fbea709f0a2c90ce...,New York University
95,H. Vincent Poor,https://s.research.com/images/b6b090da0867a494...,Princeton University
96,Daniel Rueckert,https://s.research.com/images/4e594a99fdcd9719...,Technical University of Munich
97,Xin Yao,https://s.research.com/images/2f6b369a7f558a12...,Southern University of Science and Technology
98,MengChu Zhou,https://s.research.com/images/1a8a222e0f7a9771...,New Jersey Institute of Technology
99,Martin Vetterli,https://s.research.com/images/640eab9748ff1afb...,École Polytechnique Fédérale de Lausanne
100,Dieter Fox,https://s.research.com/images/414ccd6f6fbe42e2...,University of Washington

In [27]:
df.head()

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...

In [29]:
# Get all with D-Index > 150

df[ df['D-Index'] > 150 ]

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
5,5,6,4,Philip S. Yu,University of Illinois at Chicago,United States,166,131899,"1,814",https://s.research.com/images/20815a3765631eb9...
6,6,7,5,Thomas S. Huang,University of Illinois at Urbana-Champaign,United States,165,122431,"1,329",https://s.research.com/images/ddd0e184e7830de1...
7,7,8,6,Takeo Kanade,Carnegie Mellon University,United States,161,125670,751,https://s.research.com/images/6f00a60e4fcd5fbf...
8,8,9,1,Francisco Herrera,University of Granada,Spain,161,111307,"1,008",https://s.research.com/images/900c497d066eeefc...
9,9,10,1,Wil M. P. van der Aalst,RWTH Aachen University,Germany,157,118010,"1,038",https://s.research.com/images/fe632259056863c6...
10,10,11,1,Rajkumar Buyya,University of Melbourne,Australia,156,121353,"1,058",https://s.research.com/images/2994e0b16d912fb9...
11,11,12,2,Bernhard Schölkopf,Max Planck Institute for Intelligent Systems,Germany,155,174596,"1,129",https://s.research.com/images/a9a59b6ad9d1f230...
12,12,13,2,Geoffrey E. Hinton,University of Toronto,Canada,153,443047,369,https://s.research.com/images/3a5831dd52ce7c87...
13,13,14,7,Sebastian Thrun,Stanford University,United States,152,122976,410,https://s.research.com/images/4d80db997036e941...

## Data Analysis

In [30]:
df['Affiliation'].value_counts()

University of California              125
MIT                                    62
Carnegie Mellon University             60
Microsoft (United States)              54
Stanford University                    52
                                     ...
Oregon Health & Science University      1
University of Genoa                     1
Télécom SudParis                        1
University of Quebec at Montreal        1
National Cheng Kung University          1
Name: Affiliation, Length: 558, dtype: int64

In [31]:
df['Country'].value_counts()

 United States     923
 China             188
 United Kingdom    112
 Germany            82
 Canada             77
                  ...
 Estonia             1
 Hyderabad           1
 Turkey              1
 Jordan              1
 Cyprus              1
Name: Country, Length: 66, dtype: int64

In [32]:
df.isnull().values.any()

True

In [33]:
# Check if there is any missing value
df.isnull().sum()

Unnamed: 0                0
World Rank                0
National Rank             0
Name                      0
Affiliation               0
Country                   1
D-Index                   0
Citations                 0
Number of Publications    0
Image URLs                0
dtype: int64

In [34]:
df = df.dropna(how="any") # drop all null values
df

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
...,...,...,...,...,...,...,...,...,...,...
1995,1995,1996,192,Cheng-Zhong Xu,University of Macau,China,61,11960,514,https://s.research.com/images/d1652ee8cb26ff97...
1996,1996,1997,193,Debiao He,Wuhan University,China,61,11922,228,https://s.research.com/images/97930f238ef7d9b1...
1997,1997,1998,1082,Shuai Li,University of Oulu,Finland,61,11729,395,https://s.research.com/images/607b8a3af140d2e5...
1998,1998,1999,194,Cunsheng Ding,Hong Kong University of Science and Technology,China,61,11595,228,https://s.research.com/images/1c011d0a81a71824...
1999,1999,2000,79,Jonathan Li,University of Waterloo,Canada,61,11276,505,https://s.research.com/images/90a9c3c82b5717c5...

In [35]:
df = df.reset_index(drop=True)
df

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
...,...,...,...,...,...,...,...,...,...,...
1994,1995,1996,192,Cheng-Zhong Xu,University of Macau,China,61,11960,514,https://s.research.com/images/d1652ee8cb26ff97...
1995,1996,1997,193,Debiao He,Wuhan University,China,61,11922,228,https://s.research.com/images/97930f238ef7d9b1...
1996,1997,1998,1082,Shuai Li,University of Oulu,Finland,61,11729,395,https://s.research.com/images/607b8a3af140d2e5...
1997,1998,1999,194,Cunsheng Ding,Hong Kong University of Science and Technology,China,61,11595,228,https://s.research.com/images/1c011d0a81a71824...
1998,1999,2000,79,Jonathan Li,University of Waterloo,Canada,61,11276,505,https://s.research.com/images/90a9c3c82b5717c5...

# Sorting

In [36]:
name_sorted_df = df.sort_values(by='Name')
name_sorted_df.head()

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
1671,1671,1672,11,Aapo Hyvärinen,University of Helsinki,Finland,63,65067,284,https://s.research.com/images/e3bec7c2d7ee4364...
472,472,473,21,Aaron Courville,University of Montreal,Canada,84,142816,228,https://s.research.com/images/ba1916a4e8734172...
1249,1249,1250,48,Aaron Fenster,University of Western Ontario,Canada,69,16108,543,https://s.research.com/images/91355b6c18a08d9f...
1585,1585,1586,882,Aaron Hertzmann,Adobe Systems (United States),United States,64,22872,161,https://s.research.com/images/77b4e7d37b48bde8...
994,994,995,580,Abbas El Gamal,Stanford University,United States,72,28354,243,https://s.research.com/images/c7067edb7e65fb89...

In [37]:
name_sorted_df = df.sort_values(by='Name',ascending=False)
name_sorted_df.head()

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
1417,1417,1418,798,Éva Tardos,Cornell University,United States,66,38112,182,https://s.research.com/images/8489a5fc44f4a3cf...
1987,1988,1989,1078,s muthukrishnan,Rutgers,The State University of New Jersey,61,12629,155,https://s.research.com/images/8924f9ccdd92309f...
792,792,793,1,gonzalo navarro,University of Chile,Chile,76,25496,493,https://s.research.com/images/b791f56c75f53b23...
1732,1732,1733,948,bo li,University of Illinois at Urbana-Champaign,United States,63,17803,568,https://s.research.com/images/e6fe342d1ec270e1...
731,731,732,434,Zygmunt J. Haas,The University of Texas at Dallas,United States,77,36314,321,https://s.research.com/images/d4ca1694e43e1705...

In [38]:
name_sorted_df = df.sort_values(by=['Name','Affiliation'])
name_sorted_df.head()

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
1671,1671,1672,11,Aapo Hyvärinen,University of Helsinki,Finland,63,65067,284,https://s.research.com/images/e3bec7c2d7ee4364...
472,472,473,21,Aaron Courville,University of Montreal,Canada,84,142816,228,https://s.research.com/images/ba1916a4e8734172...
1249,1249,1250,48,Aaron Fenster,University of Western Ontario,Canada,69,16108,543,https://s.research.com/images/91355b6c18a08d9f...
1585,1585,1586,882,Aaron Hertzmann,Adobe Systems (United States),United States,64,22872,161,https://s.research.com/images/77b4e7d37b48bde8...
994,994,995,580,Abbas El Gamal,Stanford University,United States,72,28354,243,https://s.research.com/images/c7067edb7e65fb89...

In [39]:
name_sorted_df = df.sort_values(by=['Affiliation','Name'])
name_sorted_df.head()

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
1611,1611,1612,893,Balachander Krishnamurthy,AT&T (United States),United States,64,18318,172,https://s.research.com/website/1049114443/imag...
1045,1045,1046,605,David S. Johnson,AT&T (United States),United States,71,112477,155,https://s.research.com/images/75ee6813942b9e9b...
360,360,361,218,Divesh Srivastava,AT&T (United States),United States,90,30362,434,https://s.research.com/images/a23448733fc7b2f9...
313,313,314,1,Christian S. Jensen,Aalborg University,Denmark,93,30669,553,https://s.research.com/images/e801bdf772a905ac...
583,583,584,2,Kim Guldstrand Larsen,Aalborg University,Denmark,81,29538,644,https://s.research.com/images/69d9fd07b90d4549...

In [40]:
name_sorted_df.sort_index(inplace=True)
name_sorted_df

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
...,...,...,...,...,...,...,...,...,...,...
1994,1995,1996,192,Cheng-Zhong Xu,University of Macau,China,61,11960,514,https://s.research.com/images/d1652ee8cb26ff97...
1995,1996,1997,193,Debiao He,Wuhan University,China,61,11922,228,https://s.research.com/images/97930f238ef7d9b1...
1996,1997,1998,1082,Shuai Li,University of Oulu,Finland,61,11729,395,https://s.research.com/images/607b8a3af140d2e5...
1997,1998,1999,194,Cunsheng Ding,Hong Kong University of Science and Technology,China,61,11595,228,https://s.research.com/images/1c011d0a81a71824...
1998,1999,2000,79,Jonathan Li,University of Waterloo,Canada,61,11276,505,https://s.research.com/images/90a9c3c82b5717c5...

# Concatenation

In [41]:
df_concat = pd.concat([df,name_sorted_df])
df_concat

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
...,...,...,...,...,...,...,...,...,...,...
1994,1995,1996,192,Cheng-Zhong Xu,University of Macau,China,61,11960,514,https://s.research.com/images/d1652ee8cb26ff97...
1995,1996,1997,193,Debiao He,Wuhan University,China,61,11922,228,https://s.research.com/images/97930f238ef7d9b1...
1996,1997,1998,1082,Shuai Li,University of Oulu,Finland,61,11729,395,https://s.research.com/images/607b8a3af140d2e5...
1997,1998,1999,194,Cunsheng Ding,Hong Kong University of Science and Technology,China,61,11595,228,https://s.research.com/images/1c011d0a81a71824...
1998,1999,2000,79,Jonathan Li,University of Waterloo,Canada,61,11276,505,https://s.research.com/images/90a9c3c82b5717c5...

In [42]:
df_concat = pd.concat([df,name_sorted_df],keys=['normal','sorted'])
df_concat

             Unnamed: 0  World Rank  National Rank               Name  \
normal 0              0           1              1       Anil K. Jain
       1              1           2              1      Yoshua Bengio
       2              2           3              2         Jiawei Han
       3              3           4              3  Michael I. Jordan
       4              4           5              1   Andrew Zisserman
...                 ...         ...            ...                ...
sorted 1994        1995        1996            192     Cheng-Zhong Xu
       1995        1996        1997            193          Debiao He
       1996        1997        1998           1082           Shuai Li
       1997        1998        1999            194      Cunsheng Ding
       1998        1999        2000             79        Jonathan Li

                                                Affiliation          Country  \
normal 0                          Michigan State University    United States
       1                             University of Montreal           Canada
       2         University of Illinois at Urbana-Champaign    United States
       3                           University of California         Berkeley
       4                               University of Oxford   United Kingdom
...                                                     ...              ...
sorted 1994                             University of Macau            China
       1995                                Wuhan University            China
       1996                              University of Oulu          Finland
       1997  Hong Kong University of Science and Technology            China
       1998                          University of Waterloo           Canada

             D-Index Citations Number of Publications  \
normal 0         203    250990                    970
       1         200    491250                    909
       2         186    209445                  1,177
       3         176    220056                    776
       4         175    255987                    698
...              ...       ...                    ...
sorted 1994       61     11960                    514
       1995       61     11922                    228
       1996       61     11729                    395
       1997       61     11595                    228
       1998       61     11276                    505

                                                    Image URLs
normal 0     https://s.research.com/images/2a967b4499197336...
       1     https://s.research.com/images/aec914cd458a74e2...
       2     https://s.research.com/images/42382fdef4ef0953...
       3     https://s.research.com/images/56e4335ff90165e8...
       4     https://s.research.com/images/2a3913cff9795e86...
...                                                        ...
sorted 1994  https://s.research.com/images/d1652ee8cb26ff97...
       1995  https://s.research.com/images/97930f238ef7d9b1...
       1996  https://s.research.com/images/607b8a3af140d2e5...
       1997  https://s.research.com/images/1c011d0a81a71824...
       1998  https://s.research.com/images/90a9c3c82b5717c5...

[3998 rows x 10 columns]

In [43]:
df_concat.loc['sorted']

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
...,...,...,...,...,...,...,...,...,...,...
1994,1995,1996,192,Cheng-Zhong Xu,University of Macau,China,61,11960,514,https://s.research.com/images/d1652ee8cb26ff97...
1995,1996,1997,193,Debiao He,Wuhan University,China,61,11922,228,https://s.research.com/images/97930f238ef7d9b1...
1996,1997,1998,1082,Shuai Li,University of Oulu,Finland,61,11729,395,https://s.research.com/images/607b8a3af140d2e5...
1997,1998,1999,194,Cunsheng Ding,Hong Kong University of Science and Technology,China,61,11595,228,https://s.research.com/images/1c011d0a81a71824...
1998,1999,2000,79,Jonathan Li,University of Waterloo,Canada,61,11276,505,https://s.research.com/images/90a9c3c82b5717c5...

In [44]:
df_concat.loc['normal']

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
...,...,...,...,...,...,...,...,...,...,...
1994,1995,1996,192,Cheng-Zhong Xu,University of Macau,China,61,11960,514,https://s.research.com/images/d1652ee8cb26ff97...
1995,1996,1997,193,Debiao He,Wuhan University,China,61,11922,228,https://s.research.com/images/97930f238ef7d9b1...
1996,1997,1998,1082,Shuai Li,University of Oulu,Finland,61,11729,395,https://s.research.com/images/607b8a3af140d2e5...
1997,1998,1999,194,Cunsheng Ding,Hong Kong University of Science and Technology,China,61,11595,228,https://s.research.com/images/1c011d0a81a71824...
1998,1999,2000,79,Jonathan Li,University of Waterloo,Canada,61,11276,505,https://s.research.com/images/90a9c3c82b5717c5...

# Apply Function

In [45]:
df.apply(lambda x: x[0])

Unnamed: 0                                                                0
World Rank                                                                1
National Rank                                                             1
Name                                                           Anil K. Jain
Affiliation                                       Michigan State University
Country                                                       United States
D-Index                                                                 203
Citations                                                            250990
Number of Publications                                                  970
Image URLs                https://s.research.com/images/2a967b4499197336...
dtype: object

In [46]:
df.apply(lambda x: x[0],axis=1)

0          0
1          1
2          2
3          3
4          4
        ...
1994    1995
1995    1996
1996    1997
1997    1998
1998    1999
Length: 1999, dtype: int64

In [47]:
df.apply(lambda x: x['Affiliation'],axis=1)

0                            Michigan State University
1                               University of Montreal
2           University of Illinois at Urbana-Champaign
3                             University of California
4                                 University of Oxford
                             ...
1994                               University of Macau
1995                                  Wuhan University
1996                                University of Oulu
1997    Hong Kong University of Science and Technology
1998                            University of Waterloo
Length: 1999, dtype: object

In [48]:
def national_top_three(rank):
  return rank <=3

national_rank = df[ df['National Rank'].apply(lambda x: national_top_three(x)) ]
national_rank

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
1,1,2,1,Yoshua Bengio,University of Montreal,Canada,200,491250,909,https://s.research.com/images/aec914cd458a74e2...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...
3,3,4,3,Michael I. Jordan,University of California,Berkeley,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
...,...,...,...,...,...,...,...,...,...,...
1862,1862,1863,2,Antonio A. F. Loureiro,Universidade Federal de Minas Gerais,Brazil,62,14570,484,https://s.research.com/images/e2c61782ea2a7b5e...
1881,1882,1883,1,Mohammad S. Obaidat,University of Jordan,Jordan,62,12966,899,https://s.research.com/images/b532535373c28db4...
1894,1895,1896,3,Eibe Frank,University of Waikato,New Zealand,61,133778,160,https://s.research.com/images/4c8d865f130dcc55...
1928,1929,1930,2,Moustafa Youssef,American University in Cairo,Egypt,61,17305,272,https://s.research.com/images/74f32cc145d7b93a...
1948,1949,1950,1,Yannis Manolopoulos,Open University of Cyprus,Cyprus,61,15397,442,https://s.research.com/images/d36b49e32dcd4ef2...

In [49]:
national_rank.sort_values(by=["Country","National Rank"])

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,Country,D-Index,Citations,Number of Publications,Image URLs
10,10,11,1,Rajkumar Buyya,University of Melbourne,Australia,156,121353,"1,058",https://s.research.com/images/2994e0b16d912fb9...
23,23,24,2,Dacheng Tao,University of Sydney,Australia,142,74454,"1,217",https://s.research.com/images/72330d26d0dcc915...
282,282,283,3,James C. Bezdek,University of Melbourne,Australia,94,74347,402,https://s.research.com/images/c9341d42d32f4150...
152,152,153,1,Thomas A. Henzinger,Institute of Science and Technology Austria,Austria,107,54669,464,https://s.research.com/images/2f5eca6562e3fea5...
171,171,172,2,Gert Pfurtscheller,Graz University of Technology,Austria,104,54135,378,https://s.research.com/images/ba6aa74167d15d2d...
...,...,...,...,...,...,...,...,...,...,...
4,4,5,1,Andrew Zisserman,University of Oxford,United Kingdom,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
44,44,45,2,Zidong Wang,Brunel University London,United Kingdom,130,52986,852,https://s.research.com/images/58bbd9d83bb85b8f...
45,45,46,3,Nicholas R. Jennings,Loughborough University,United Kingdom,129,83550,723,https://s.research.com/images/3ac5b504ec1dd4d0...
0,0,1,1,Anil K. Jain,Michigan State University,United States,203,250990,970,https://s.research.com/images/2a967b4499197336...
2,2,3,2,Jiawei Han,University of Illinois at Urbana-Champaign,United States,186,209445,"1,177",https://s.research.com/images/42382fdef4ef0953...

# Aggregate

In [50]:
country_presence = df.groupby('Country')
country_presence.first()

,Unnamed: 0,World Rank,National Rank,Name,Affiliation,D-Index,Citations,Number of Publications,Image URLs
Country,,,,,,,,,
Australia,10,11,1,Rajkumar Buyya,University of Melbourne,156,121353,"1,058",https://s.research.com/images/2994e0b16d912fb9...
Austria,152,153,1,Thomas A. Henzinger,Institute of Science and Technology Austria,107,54669,464,https://s.research.com/images/2f5eca6562e3fea5...
Baltimore County,197,198,123,Tim Finin,University of Maryland,101,49841,579,https://s.research.com/images/49745edf0a51c611...
Belgium,128,129,1,Marco Dorigo,Université Libre de Bruxelles,110,140006,521,https://s.research.com/images/7c9e5565640fb89a...
Berkeley,3,4,3,Michael I. Jordan,University of California,176,220056,776,https://s.research.com/images/56e4335ff90165e8...
...,...,...,...,...,...,...,...,...,...
Turkey,1844,1845,1,Murat Uysal,Özyeğin University,62,16640,437,https://s.research.com/images/43ec08467f4a3d5b...
US,563,564,328,Jonathan J. Hull,Independent Scientist / Consultant,82,21433,328,https://s.research.com/images/2f79ee5bc28f1f72...
United Arab Emirates,37,38,1,Ian F. Akyildiz,Technology Innovation Institute,131,126102,601,https://s.research.com/images/7191b523b8868133...
United Kingdom,4,5,1,Andrew Zisserman,University of Oxford,175,255987,698,https://s.research.com/images/2a3913cff9795e86...
United States,0,1,1,Anil K. Jain,Michigan State University,203,250990,970,https://s.research.com/images/2a967b4499197336...

In [51]:
country_presence.describe()

                      Unnamed: 0                                            \
                           count         mean         std     min      25%
Country
 Australia                  51.0  1173.764706  527.466874    10.0   852.50
 Austria                    13.0   880.307692  622.492488   152.0   319.00
 Baltimore County            5.0   949.400000  605.391444   197.0   422.00
 Belgium                    23.0  1036.782609  497.620516   128.0   660.00
 Berkeley                   45.0   642.377778  601.038922     3.0   106.00
...                          ...          ...         ...     ...      ...
 Turkey                      1.0  1844.000000         NaN  1844.0  1844.00
 US                          1.0   563.000000         NaN   563.0   563.00
 United Arab Emirates        3.0   267.000000  213.550931    37.0   171.00
 United Kingdom            112.0   949.767857  573.262592     4.0   440.25
 United States             923.0   972.124594  572.376833     0.0   498.00

                                              World Rank               ...  \
                          50%     75%     max      count         mean  ...
Country                                                                ...
 Australia             1185.0  1597.0  1969.0       51.0  1174.764706  ...
 Austria                839.0  1595.0  1854.0       13.0   881.307692  ...
 Baltimore County      1152.0  1472.0  1504.0        5.0   950.400000  ...
 Belgium               1050.0  1254.0  1944.0       23.0  1037.782609  ...
 Berkeley               456.0  1047.0  1932.0       45.0   643.377778  ...
...                       ...     ...     ...        ...          ...  ...
 Turkey                1844.0  1844.0  1844.0        1.0  1845.000000  ...
 US                     563.0   563.0   563.0        1.0   564.000000  ...
 United Arab Emirates   305.0   382.0   459.0        3.0   268.000000  ...
 United Kingdom         858.5  1464.5  1963.0      112.0   950.767857  ...
 United States          950.0  1457.0  1994.0      923.0   973.124594  ...

                      National Rank         D-Index                         \
                                75%     max   count        mean        std
Country
 Australia                    38.50    52.0    51.0   73.941176  17.896829
 Austria                      10.00    13.0    13.0   79.769231  15.471231
 Baltimore County            824.00   840.0     5.0   77.800000  15.706686
 Belgium                      17.50    23.0    23.0   74.608696  11.858020
 Berkeley                    607.00  1056.0    45.0   93.822222  28.575489
...                             ...     ...     ...         ...        ...
 Turkey                        1.00     1.0     1.0   62.000000        NaN
 US                          328.00   328.0     1.0   82.000000        NaN
 United Arab Emirates          1.50     2.0     3.0  103.000000  24.576411
 United Kingdom               85.25   113.0   112.0   78.285714  17.134039
 United States               818.50  1081.0   923.0   78.426869  18.195784


                        min   25%   50%    75%    max
Country
 Australia             61.0  64.0  70.0   75.0  156.0
 Austria               62.0  64.0  75.0   92.0  107.0
 Baltimore County      65.0  66.0  70.0   87.0  101.0
 Belgium               61.0  68.5  71.0   79.0  110.0
 Berkeley              61.0  71.0  85.0  114.0  176.0
...                     ...   ...   ...    ...    ...
 Turkey                62.0  62.0  62.0   62.0   62.0
 US                    82.0  82.0  82.0   82.0   82.0
 United Arab Emirates  85.0  89.0  93.0  112.0  131.0
 United Kingdom        61.0  66.0  74.5   86.0  175.0
 United States         61.0  66.0  73.0   83.5  203.0

[66 rows x 32 columns]

In [54]:
country_presence['National Rank'].mean()

Country
 Australia                25.588235
 Austria                   7.000000
 Baltimore County        541.400000
 Belgium                  12.000000
 Berkeley                369.444444
                            ...
 Turkey                    1.000000
 US                      328.000000
 United Arab Emirates      1.333333
 United Kingdom           57.321429
 United States           551.425785
Name: National Rank, Length: 66, dtype: float64

In [55]:
country_and_university_presence = df.groupby(['Country','Affiliation'])
country_and_university_presence.first()

                                                                   Unnamed: 0  \
Country        Affiliation
 Australia     Australian National University                             682
               Commonwealth Scientific and Industrial Research...        1080
               Curtin University                                         1409
               Deakin University                                         1316
               Griffith University                                       1709
...                                                                       ...
 United States Worcester Polytechnic Institute                           1557
               Yale University                                            693
               ZapFraud                                                  1232
               Zillow Group (United States)                               560
               you.com                                                    984

                                                                   World Rank  \
Country        Affiliation
 Australia     Australian National University                             683
               Commonwealth Scientific and Industrial Research...        1081
               Curtin University                                         1410
               Deakin University                                         1317
               Griffith University                                       1710
...                                                                       ...
 United States Worcester Polytechnic Institute                           1558
               Yale University                                            694
               ZapFraud                                                  1233
               Zillow Group (United States)                               561
               you.com                                                    985

                                                                   National Rank  \
Country        Affiliation
 Australia     Australian National University                                 10
               Commonwealth Scientific and Industrial Research...             18
               Curtin University                                              32
               Deakin University                                              30
               Griffith University                                            42
...                                                                          ...
 United States Worcester Polytechnic Institute                               864
               Yale University                                               409
               ZapFraud                                                      711
               Zillow Group (United States)                                  327
               you.com                                                       575

                                                                                    Name  \
Country        Affiliation
 Australia     Australian National University                            Richard Hartley
               Commonwealth Scientific and Industrial Research...             Toby Walsh
               Curtin University                                            Xiangyu Wang
               Deakin University                                        Svetha Venkatesh
               Griffith University                                     Kuldip K. Paliwal
...                                                                                  ...
 United States Worcester Polytechnic Institute                     Elke A. Rundensteiner
               Yale University                                        Leandros Tassiulas
               ZapFraud                                                 Markus Jakobsson
               Zillow Group (United States)                               Sing Bing Kang
               you.com                                                    Richard Socher

                                                                   D-Index  \
Country        Affiliation
 Australia     Australian National University                           78
               Commonwealth Scientific and Industrial Research...       71
               Curtin University                                        67
               Deakin University                                        68
               Griffith University                                      63
...                                                                    ...
 United States Worcester Polytechnic Institute                          65
               Yale University                                          78
               ZapFraud                                                 69
               Zillow Group (United States)                             82
               you.com                                                  72

                                                                  Citations  \
Country        Affiliation
 Australia     Australian National University                         70243
               Commonwealth Scientific and Industrial Research...     22398
               Curtin University                                      13600
               Deakin University                                      17408
               Griffith University                                    20580
...                                                                     ...
 United States Worcester Polytechnic Institute                        13146
               Yale University                                        32264
               ZapFraud                                               18271
               Zillow Group (United States)                           24645
               you.com                                               108582

                                                                  Number of Publications  \
Country        Affiliation
 Australia     Australian National University                                        377
               Commonwealth Scientific and Industrial Research...                    416
               Curtin University                                                     389
               Deakin University                                                     769
               Griffith University                                                   360
...                                                                                  ...
 United States Worcester Polytechnic Institute                                       561
               Yale University                                                       509
               ZapFraud                                                              212
               Zillow Group (United States)                                          296
               you.com                                                               201

                                                                                                          Image URLs
Country        Affiliation
 Australia     Australian National University                      https://s.research.com/images/a2eb08b356a3f291...
               Commonwealth Scientific and Industrial Research...  https://s.research.com/images/27d7ff0f7401e659...
               Curtin University                                   https://s.research.com/images/cd1125e8c229d79e...
               Deakin University                                   https://s.research.com/images/a2e164ed0bf34c92...
               Griffith University                                 https://s.research.com/images/b05a2feb697b3b35...
...                                                                                                              ...
 United States Worcester Polytechnic Institute                     https://s.research.com/images/9cac1b90dedd50cf...
               Yale University                                     https://s.research.com/images/b1264cb1b432aad0...
               ZapFraud                                            https://s.research.com/images/d6c9cac7ce7ebb2f...
               Zillow Group (United States)                        https://s.research.com/images/c0baad35f59865dc...
               you.com                                             https://s.research.com/images/e3b2e4cdaafe7d83...

[567 rows x 8 columns]

In [57]:
country_and_university_presence['D-Index'].mean()

Country         Affiliation
 Australia      Australian National University                                  75.0
                Commonwealth Scientific and Industrial Research Organisation    71.0
                Curtin University                                               64.0
                Deakin University                                               68.0
                Griffith University                                             63.0
                                                                                ...
 United States  Worcester Polytechnic Institute                                 65.0
                Yale University                                                 72.5
                ZapFraud                                                        69.0
                Zillow Group (United States)                                    82.0
                you.com                                                         72.0
Name: D-Index, Length: 567, dtype: float64

In [58]:
country_and_university_presence['D-Index'].median()

Country         Affiliation
 Australia      Australian National University                                  75.0
                Commonwealth Scientific and Industrial Research Organisation    71.0
                Curtin University                                               64.0
                Deakin University                                               68.0
                Griffith University                                             63.0
                                                                                ...
 United States  Worcester Polytechnic Institute                                 65.0
                Yale University                                                 73.5
                ZapFraud                                                        69.0
                Zillow Group (United States)                                    82.0
                you.com                                                         72.0
Name: D-Index, Length: 567, dtype: float64

### Cross Tab

In [59]:
pd.crosstab(df["Country"],df["Affiliation"],margins=True)

Affiliation,AT&T (United States),Aalborg University,Aalto University,Aarhus University,Adobe Systems (United States),Agency for Science,Alfréd Rényi Institute of Mathematics,Algorand Foundation,Alibaba Group (China),Allen Institute for Artificial Intelligence,...,ZapFraud,Zhejiang University,Zillow Group (United States),you.com,École Normale Supérieure,École Polytechnique Fédérale de Lausanne,École de Technologie Supérieure,École des Ponts ParisTech,Özyeğin University,All
Country,,,,,,,,,,,,,,,,,,,,,
Australia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,51
Austria,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,13
Baltimore County,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
Belgium,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,23
Berkeley,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
US,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
United Arab Emirates,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
United Kingdom,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,112
United States,3,0,0,0,2,0,0,0,0,1,...,1,0,1,1,0,0,0,0,0,923
All,3,4,4,2,2,1,1,2,2,1,...,1,9,1,1,5,20,1,1,1,1999

In [60]:
df['Affiliation'].value_counts()

University of California                       125
MIT                                             62
Carnegie Mellon University                      60
Microsoft (United States)                       54
Stanford University                             52
                                              ...
Southeast University                             1
Universidad Publica De Navarra                   1
Max Planck Society                               1
Allen Institute for Artificial Intelligence      1
National Cheng Kung University                   1
Name: Affiliation, Length: 557, dtype: int64

In [61]:
for key, count in df['Affiliation'].value_counts().items():
  if key == "Zhejiang University":
    print(count)

9

In [62]:
df['Country'].value_counts()

 United States     923
 China             188
 United Kingdom    112
 Germany            82
 Canada             77
                  ...
 Estonia             1
 Hyderabad           1
 Turkey              1
 Jordan              1
 Cyprus              1
Name: Country, Length: 66, dtype: int64

### Pivot Table

In [64]:
pd.pivot_table(df,index=['Country','Affiliation'],values='D-Index',aggfunc=[np.mean, np.median, min, max, np.std])

                                                                     mean  \
                                                                  D-Index
Country        Affiliation
 Australia     Australian National University                        75.0
               Commonwealth Scientific and Industrial Research...    71.0
               Curtin University                                     64.0
               Deakin University                                     68.0
               Griffith University                                   63.0
...                                                                   ...
 United States Worcester Polytechnic Institute                       65.0
               Yale University                                       72.5
               ZapFraud                                              69.0
               Zillow Group (United States)                          82.0
               you.com                                               72.0

                                                                   median  \
                                                                  D-Index
Country        Affiliation
 Australia     Australian National University                        75.0
               Commonwealth Scientific and Industrial Research...    71.0
               Curtin University                                     64.0
               Deakin University                                     68.0
               Griffith University                                   63.0
...                                                                   ...
 United States Worcester Polytechnic Institute                       65.0
               Yale University                                       73.5
               ZapFraud                                              69.0
               Zillow Group (United States)                          82.0
               you.com                                               72.0

                                                                      min  \
                                                                  D-Index
Country        Affiliation
 Australia     Australian National University                          72
               Commonwealth Scientific and Industrial Research...      71
               Curtin University                                       61
               Deakin University                                       68
               Griffith University                                     63
...                                                                   ...
 United States Worcester Polytechnic Institute                         65
               Yale University                                         65
               ZapFraud                                                69
               Zillow Group (United States)                            82
               you.com                                                 72

                                                                      max  \
                                                                  D-Index
Country        Affiliation
 Australia     Australian National University                          78
               Commonwealth Scientific and Industrial Research...      71
               Curtin University                                       67
               Deakin University                                       68
               Griffith University                                     63
...                                                                   ...
 United States Worcester Polytechnic Institute                         65
               Yale University                                         78
               ZapFraud                                                69
               Zillow Group (United States)                            82
               you.com                                                 72

                                                                        std
                                                                    D-Index
Country        Affiliation
 Australia     Australian National University                      4.242641
               Commonwealth Scientific and Industrial Research...       NaN
               Curtin University                                   4.242641
               Deakin University                                        NaN
               Griffith University                                      NaN
...                                                                     ...
 United States Worcester Polytechnic Institute                          NaN
               Yale University                                     6.137318
               ZapFraud                                                 NaN
               Zillow Group (United States)                             NaN
               you.com                                                  NaN

[567 rows x 5 columns]

In [65]:
pd.pivot_table(df,index=['Country','Affiliation'],values=['D-Index','National Rank'],aggfunc=[np.mean, np.median, min, max, np.std])

                                                                     mean  \
                                                                  D-Index
Country        Affiliation
 Australia     Australian National University                        75.0
               Commonwealth Scientific and Industrial Research...    71.0
               Curtin University                                     64.0
               Deakin University                                     68.0
               Griffith University                                   63.0
...                                                                   ...
 United States Worcester Polytechnic Institute                       65.0
               Yale University                                       72.5
               ZapFraud                                              69.0
               Zillow Group (United States)                          82.0
               you.com                                               72.0

                                                                                 \
                                                                  National Rank
Country        Affiliation
 Australia     Australian National University                              12.5
               Commonwealth Scientific and Industrial Research...          18.0
               Curtin University                                           40.5
               Deakin University                                           30.0
               Griffith University                                         42.0
...                                                                         ...
 United States Worcester Polytechnic Institute                            864.0
               Yale University                                            584.5
               ZapFraud                                                   711.0
               Zillow Group (United States)                               327.0
               you.com                                                    575.0

                                                                   median  \
                                                                  D-Index
Country        Affiliation
 Australia     Australian National University                        75.0
               Commonwealth Scientific and Industrial Research...    71.0
               Curtin University                                     64.0
               Deakin University                                     68.0
               Griffith University                                   63.0
...                                                                   ...
 United States Worcester Polytechnic Institute                       65.0
               Yale University                                       73.5
               ZapFraud                                              69.0
               Zillow Group (United States)                          82.0
               you.com                                               72.0

                                                                                 \
                                                                  National Rank
Country        Affiliation
 Australia     Australian National University                              12.5
               Commonwealth Scientific and Industrial Research...          18.0
               Curtin University                                           40.5
               Deakin University                                           30.0
               Griffith University                                         42.0
...                                                                         ...
 United States Worcester Polytechnic Institute                            864.0
               Yale University                                            545.0
               ZapFraud                                                   711.0
               Zillow Group (United States)                               327.0
               you.com                                                    575.0

                                                                      min  \
                                                                  D-Index
Country        Affiliation
 Australia     Australian National University                          72
               Commonwealth Scientific and Industrial Research...      71
               Curtin University                                       61
               Deakin University                                       68
               Griffith University                                     63
...                                                                   ...
 United States Worcester Polytechnic Institute                         65
               Yale University                                         65
               ZapFraud                                                69
               Zillow Group (United States)                            82
               you.com                                                 72

                                                                                 \
                                                                  National Rank
Country        Affiliation
 Australia     Australian National University                                10
               Commonwealth Scientific and Industrial Research...            18
               Curtin University                                             32
               Deakin University                                             30
               Griffith University                                           42
...                                                                         ...
 United States Worcester Polytechnic Institute                              864
               Yale University                                              409
               ZapFraud                                                     711
               Zillow Group (United States)                                 327
               you.com                                                      575

                                                                      max  \
                                                                  D-Index
Country        Affiliation
 Australia     Australian National University                          78
               Commonwealth Scientific and Industrial Research...      71
               Curtin University                                       67
               Deakin University                                       68
               Griffith University                                     63
...                                                                   ...
 United States Worcester Polytechnic Institute                         65
               Yale University                                         78
               ZapFraud                                                69
               Zillow Group (United States)                            82
               you.com                                                 72

                                                                                 \
                                                                  National Rank
Country        Affiliation
 Australia     Australian National University                                15
               Commonwealth Scientific and Industrial Research...            18
               Curtin University                                             49
               Deakin University                                             30
               Griffith University                                           42
...                                                                         ...
 United States Worcester Polytechnic Institute                              864
               Yale University                                              839
               ZapFraud                                                     711
               Zillow Group (United States)                                 327
               you.com                                                      575

                                                                        std  \
                                                                    D-Index
Country        Affiliation
 Australia     Australian National University                      4.242641
               Commonwealth Scientific and Industrial Research...       NaN
               Curtin University                                   4.242641
               Deakin University                                        NaN
               Griffith University                                      NaN
...                                                                     ...
 United States Worcester Polytechnic Institute                          NaN
               Yale University                                     6.137318
               ZapFraud                                                 NaN
               Zillow Group (United States)                             NaN
               you.com                                                  NaN


                                                                  National Rank
Country        Affiliation
 Australia     Australian National University                          3.535534
               Commonwealth Scientific and Industrial Research...           NaN
               Curtin University                                      12.020815
               Deakin University                                            NaN
               Griffith University                                          NaN
...                                                                         ...
 United States Worcester Polytechnic Institute                              NaN
               Yale University                                       204.995122
               ZapFraud                                                     NaN
               Zillow Group (United States)                                 NaN
               you.com                                                      NaN

[567 rows x 10 columns]